#Tokenizer Settings
tokenizer_settings:
  tokenizer_type: mbert_single
  init:
    pretrained_model_name_or_path: bert-base-multilingual-cased
  tokenization:
    max_length: 256
    truncation: True
    return_token_type_ids: False
    return_tensors: pt