#Tokenizer Settings
tokenizer_settings:
  tokenizer_type: xlmr_tokenizer
  init:
    pretrained_model_name_or_path: xlm-roberta-base
  tokenization:
    max_length: 256
    truncation: True
    padding: max_length
    return_token_type_ids: False
    return_tensors: pt