#Training Settings
expected_batch_size: 32
visible_devices: "0,1"
n_gpu: 2
training_arguments:
  per_device_train_batch_size: 16
  gradient_accumulation_steps: 1
  learning_rate: 2.0e-5
  num_train_epochs: 40
  evaluation_strategy: 'no'
  warmup_ratio: .01
  logging_steps: 25
  save_steps: 7500
  save_total_limit: 1